services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: music_db
      MYSQL_USER: user
      MYSQL_PASSWORD: encoding1105
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./vite-react-music-app/backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./vite-react-music-app/backend
    container_name: music_backend
    restart: always
    depends_on:
      - mysql
    env_file:
      - ./vite-react-music-app/backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./vite-react-music-app/backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  frontend:
    build: ./vite-react-music-app/frontend
    container_name: music_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./vite-react-music-app/frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  db_data:
